- packages/api/src/test/loo_routes.test.js
Previously, when tests were running in a scenario in which the `gbptm-test` database had not been created by previous testing, the tests would fail, with mongoose blaming a lack of geo indexes.
This could be reproduced locally, as well as in the CI environment, by dropping the `gbptm-test` database.
This fix ensures that these indexes have been created before tests are run, however, it is likely that this could be a symptom of a greater problem with how we are using mongoose's sometimes unpredictably ordered operations.
> CI Test Fix

- packages/api/src/index.js
- packages/api/src/models/loo.js
- packages/api/src/models/loo_schema.js
- packages/api/src/routes/public/loo.js
- packages/api/src/routes/public/search.js
* Fixes the family of exploits described in f7de9b5
* Generally attempts to interpret query and parameter values as soon as possible to avoid similar issues and tidy the code a little
I'm unsure as to whether tests should be made to check for this particular exploit. Although it would be nice to know one exploit we're safe from, it would be a very specific test and it might be sufficient instead to simply test that strange parameters and queries are handled properly when properly covering the `api` package with tests.
> Query sanitisation

- packages/ui/src/pages/AddEditPage.js
See #200.
This can be extended to more of the form's description if necessary, else this should be ready for merging.
> fix: describe add/edit page appropriately

- packages/ui/src/components/css/edit-loo-map.module.css
closes #180 
This was fixed just be bumping up the z-index.
Alternative solutions considered:
* **Using leaflet's API to add a new layer/pane** - leaflet doesn't provide any abstraction beyond dealing with z-indexes through its API if one wishes to guarantee how its elements stack, so this would've required JavaScript and increased the complexity of the solution dramatically
* **Using relative z-indexes and clever CSS to always ensure the crosshair is higher than the map's container** - I couldn't find a way to give a stacking context in the parent node of the map without changing visible CSS properties undesirably; maybe somebody better at CSS could work out how to do this?
The current solution should suffice unless we find this to be a regular issue on updating our leaflet dependency.
> fix: adjust z-index so crosshair is visible

- packages/api/src/config/config.js
- packages/api/src/models/loo.js
- packages/api/src/routes/loos.js
- packages/api/src/test/loo_routes.test.js
- packages/ui/src/api.js
- packages/ui/src/components/map/LooMap.js
- packages/ui/src/components/map/NearestLooMap.js
- packages/ui/src/config.js
- packages/ui/src/pages/HomePage.js
closes #185
The quantity limit has been removed and so this is no longer an issue. Nearby loos are now only limited by distance, which has been given a maximum and a modest default within the API.
closes #186
Our current API function [deconstructs its limit arguments](https://github.com/neontribe/gbptm/blob/3277b5d6dc95833db70303d94fd15c1c54b09391/packages/ui/src/api.js#L8) but, despite this, everywhere it is called [we are passing a single number instead of an object](https://github.com/neontribe/gbptm/blob/3277b5d6dc95833db70303d94fd15c1c54b09391/packages/ui/src/redux/sagas/loos.js#L24). This was leading us to have both limit and radius as undefined within the function, hitting the API endpoint with an empty query value for limit and hence falling back on what was then the default of …
> Nearby Loo Improvements

- packages/api/src/models/loo.js
- packages/ui/src/pages/AddEditPage.js
closes #224
Fixed a number of bugs here:
* When regenerating a loo from its reports, the latest geometry was found [but not used to replace the existing geometry](https://github.com/neontribe/gbptm/compare/moving-duplicate?expand=1#diff-b7c5fc8aec753bf09eac5e21f01f078cR119)
* While reports had been slimmed down, [we were still sending the old values](https://github.com/neontribe/gbptm/compare/moving-duplicate?expand=1#diff-042b23d2cad108ca540ba50cc64cfae1L132)
* We had [stopped citing the reports we had derived new reports from](https://github.com/neontribe/gbptm/compare/moving-duplicate?expand=1#diff-042b23d2cad108ca540ba50cc64cfae1R170) following slimming reports down
All in all, when loos are moved now, they should actually be moved. Editing their properties should now also work as …
> Moving a loo too far duplicates it

- packages/ui/src/index.js
The absence of `array.prototype.find` was causing problems in IE11. Adding a polyfill for this function mitigates that.
> fix: add array.prototype.find polyfill for IE support

- packages/ui/src/pages/LooPage.js
* **Prefer walking directions (`dirflg=w`)**
* **Start the user at their current location (no `saddr` param)**
Although providing `saddr=here` would start users at their current location on desktops, it would not on the native Android navigation app, instead starting them at the unknown position `here`. This fixes this, at the cost of Google Maps opening with no starting location in desktop browsers. Though untested, it is expected that Apple devices will see no change from this, as Apple states that `saddr` defaults to `here`.
> Map linking improvements

- packages/ui/src/pages/css/home-page.module.css
> fix: avoid overlapping IE11 sidebar text

- packages/ui/src/images/pref-accessible-white.svg
- packages/ui/src/images/pref-accessible.svg
- packages/ui/src/images/pref-babychanging-white.svg
- packages/ui/src/images/pref-babychanging.svg
- packages/ui/src/images/pref-cost-white.svg
- packages/ui/src/images/pref-cost.svg
- packages/ui/src/images/pref-female-white.svg
- packages/ui/src/images/pref-female.svg
- packages/ui/src/images/pref-male-white.svg
- packages/ui/src/images/pref-male.svg
- packages/ui/src/images/pref-open-true.svg
- packages/ui/src/images/pref-open-white.svg
- packages/ui/src/images/pref-open.svg
fixes #195 
IE lte 11 needs a `viewBox` attribute to scale correctly.
Perhaps we could find a way to lint for this?
Also, these assets could definitely be minified.
> fix: add viewBox attr to svg's

- packages/ui/src/config.js
- packages/ui/src/pages/AddEditPage.js
- packages/ui/src/pages/LooPage.js
This branch generally overhauls our humanization code for property values, fixing a number of issues:
* [We didn't include properties we didn't know the order of](https://github.com/neontribe/gbptm/commit/f4e1acb9a79de8484ed025d57b38799e8380032b)
* [We humanized all property values, even those that were already human-readable](https://github.com/neontribe/gbptm/commit/6d1dd1d82e5301da0cf429886e3220d600ed39e9), causing issues such as #223 (as a result, this closes #233)
One side-effect of fixing this issue is that the `fee` field may sometimes show as `false`, instead of `No` as before. This is because the `fee` field is, for the most part, human-readable and editable, and there is no practical way to distinguish between a user-entered `false` string and a pre-existing one.
To avoid …
> Loo prop humanization

- packages/ui/src/components/css/layout.module.css
closes #236
The previous media query was a little too specific:
* Landscape devices with thin screens were not targeted
* Devices with large screens but smaller browser windows were not targeted
The new media query cares only about the width of the viewport, fixing #236.
> fix: be less specific about what a small viewport is

- packages/ui/src/pages/AddEditPage.js
- packages/ui/src/pages/HomePage.js
- packages/ui/src/pages/LooPage.js
- packages/ui/src/pages/RemovePage.js
Replaced word "loo" with "toilet" in writing, for better consistency.
closes #258
This changed:
* The Home page
* The Add/Edit page
* Loading messages across the rest of the site
The about page is left unchanged, as it is to be re-written before release anyway.
> fix: use word toilet instead of loo in text

- packages/ui/src/components/LooMap.js
closes #265
On displays that `leaflet` considered to be retina, icons would appear oversized. This was because the styling that should've resized them was applied to their parent, not the `<img>` tag itself.
This was not manifested in non-labeled markers as we were just using a single `<img>` tag as the marker, which correctly received the styling.
To correct this, the image was given as a `background` styling property for the marker div instead of in an `<img>` within it.
> fix: styling of numbered markers on displays marked by leaflet as retina

- packages/ui/src/components/NearestLooMap.js
- packages/ui/src/pages/HomePage.js
- packages/ui/src/redux/modules/loos.js
- packages/ui/src/redux/sagas/loos.js
closes #249
Previously, we only had a loading indicator for map tiles. This wasn't much good for working out if you were waiting for nearer loos to load in. Now:
* **The `leaflet` map spinner is spun when nearby loos are being fetched** - [this was added](https://github.com/neontribe/gbptm/compare/unity...loading-indicator#diff-27a3e73b51939405340ccd887244536f) the [only way `leaflet-loading` allows](https://github.com/ebrelsford/Leaflet.loading/blob/bfc810ea31f55e0a30ed65cbb0bf7f8bfc857bce/README.md#usage), with events, which is unfortunately quite un-React
* **On the mobile list-view of nearby toilets, a loading message is shown instead of the toilets for the previous query, to ensure stale toilet results aren't shown** - this was added as a loading boolean in the redux state, as we …
> Loading indicator enhancements

- packages/ui/src/components/LooMap.js
- packages/ui/src/components/NearestLooMap.js
- packages/ui/src/pages/LooPage.js
closes #241
Clustering was [enabled everywhere](https://github.com/neontribe/gbptm/commit/fa6d54d5d3198a35dd6c0213b86eba72a9403458). Prior to this, we had separate branched implementations for clustered and unclustered `LooMap`s. We no longer had the explicit need to disable clustering, so we were able to scoop up some cheap maintainability by removing the unclustered implementation.
Previously, on every render we regenerated all markers. There were a few issues with this:
* Obvious performance hit, especially in areas such as London with over 1000 loos within 50km
* Clustering was not deterministic and, as such, on moving cluster sizes would visibly change even when the loos in the area had not
One would hope that React could be used to reduce some of this effort but, sadly, the …
> Clustering improvements

- packages/api/src/models/loo.js
- packages/ui/src/components/LooMap.js
Just a small contribution to #233:
We served loos in their entirety in our near loos endpoint, however, we only need loo coordinates for the map markers and some basic property values for the user's preference icons. This limits the loos in the response to just these properties, leading to nearly 75% smaller response sizes in most scenarios.
> Scope optimisations

- packages/ui/src/components/LooListItem.js
- packages/ui/src/components/LooMap.js
- packages/ui/src/components/NearestLooMap.js
- packages/ui/src/pages/AboutPage.js
- packages/ui/src/pages/HomePage.js
- packages/ui/src/pages/LooPage.js
closes #285
Previously, we were deciding whether to number loos or not based on whether the `countLimit` prop in `LooMap` was null, which didn't make much sense. Further, this was implemented incorrectly in `NearestLooMap`, which was setting `countFrom` to `null` in an attempt to stifle counting; counting was only disabled on the single loo page because we were misusing another one of `NearestLooMap`'s props.
Now, `countLimit` is just set to 0 to turn off counting in `LooMap`. `NearestLooMap` uses this to enable or disable counting (as decided by its own `numberNearest` property).
This fixes the issue at #285 where loos would be numbered from `0` to `5` when one was attempting to disable counting with `NearestLooMap`'s `numberNearest` prop.
> fix: number loos on only the Home and About page

- packages/ui/src/pages/css/loo-page.module.css
closes #253
Sometimes property values have newlines in them; this alteration to the CSS ensures that they're displayed.
> fix: show newlines in loo property values

- packages/ui/src/components/LooMap.js
- packages/ui/src/components/css/loo-map.module.css
- packages/ui/src/pages/AddEditPage.js
closes #248
closes #272
Everywhere we showed the center marker, we now show the crosshair instead. This means that we show the crosshair everywhere except the individual loo page and remove page, as relative distances/numbering are not used there.
Within the source, the crosshair is now under the control of `showCenter` and the old crosshair-specific props have been removed.
If the crosshair is too loud, we could look at making it less so for scenarios in which the location of a loo is not being determined (e.g. through opacity, relative size to viewport, etc).
> feat: replace center marker circle with crosshair

- packages/ui/src/pages/HomePage.js
We do this since the mapConteols.center will be set even if gelocation
is denied or fails. fixes #301
> fix: use mapControls rather than geolocation

- packages/ui/src/redux/sagas/loos.js
* Rename variable from `remove` -> `to_remove` to avoid confusion with `remove` generator.
* Call `remove` instead of `report` to remove loos
* Pass correct `looId` and `reason` to remove method call.
> fix: fix method & data used when deleting pending loos

- packages/admin/example.env
- packages/admin/package.json
- packages/admin/src/components/AppLayout.js
- packages/admin/src/components/Search.js
- packages/admin/src/components/Statistics.js
- packages/admin/src/components/stats/AreaComparisonStats.js
- packages/admin/src/components/stats/HeadlineStats.js
- packages/admin/src/index.js
- packages/admin/src/lib/settings.js
- yarn.lock
resolves https://github.com/neontribe/gbptm/issues/349
* Substitute react-router with reach-router
* Test paths to ensure functionality remains the same
* The `navigate` method provided by `reach-router` is now used instead of `.push` to navigate to routes.
* State is now passed around on the `props.location.state` object instead of `props.location.query`. Hence we now use `props.location.state.query` in a lot of places.
> 4 move to reach router

- packages/admin/package.json
- packages/admin/src/components/Search.js
- packages/api/src/routes/search.js
- yarn.lock
resolves #352 
* Implements an autocomplete search box for contributors using the method recommended in the material-ui docs.
* Adds the "Downshift" library which handles state, with the text input and suggestions being passed in using render props.
* Loads in contributors using the `/statistics/contributors` endpoint.
* Includes a button to easily clear the input.
* Handles a new `attributions` param in the API to look up toilets attributed to a specific contributor.
> 352 search by contributor

- packages/admin/src/components/AppLayout.js
- packages/admin/src/components/LooTable.js
- packages/admin/src/components/LooTile.js
- packages/admin/src/components/LooView.js
- packages/admin/src/components/Search.js
- packages/admin/src/components/stats/AreaComparisonStats.js
- packages/admin/src/index.js
- packages/api/src/routes/loos.js
- packages/api/src/routes/search.js
resolves: #348
* Adds two new components, LooTable & LooView.
* LooTable displays properties attached to loos.
* LooView displays information about specific loos.
* LooView registers the /admin/loos/:loo path.
* Displays report history using a bootstrap accordion.
* Modifies LooTile so it can be used outside of a GridList, also allows you to pass in multiple custom classes using the `classnames` lib.
* Adds a query param `?populateReports=true` to the /loos/:id endpoint on the API to require reports to be loaded.
* Refactors `search.js` in the API adding to code clarity.
* Includes a (hopeful (~_untested_~)) fix for the /admin routing issue
> feat: implement a loo detail page

- packages/admin/src/components/LooTable.js
- packages/admin/src/components/LooView.js
- packages/admin/src/components/Search.js
- packages/admin/src/components/SearchAutocomplete.js
- packages/admin/src/components/table/LooTable.js
- packages/admin/src/components/table/LooTablePaginationActions.js
- packages/admin/src/lib/utils.js
resolves #356 #357 
* Moves the Downshift autocomplete into its own component to reduce the LoC in Search.js and make the code more readable
* Moves search results into a table component.
* Expands the functionality of the LooTable component
* Provides three new render props to customise the table: `<TableHead>`, `<TableBody>` and `<TableFooter>`
* Implements pagination based off of the API search results
* Simplification of some of the search logic.
> 357 search results table

- packages/api/src/db/loo.js
- packages/api/src/db/report.js
* Loos generated from reports were solely relying upon ID generation when unrolling the loo roll (AKA Report List).
* I have modified this process so that if an ID is available it is used first, with the ID generation used as a fallback only if that is not available.
> 392 second toilet appearing

- packages/ui/src/pages/AddEditPage.js
* This ensures that all questionnaire values are converted into a null value before being sent to the backend if the user chooses to remove the value.
> fix: conv str to null value so field removed in mongoose

- README.md
Currently, if git isn't setup for ssh you'll get 
```
Cloning into 'gbptm'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```
As the repo is public, we don't need access via ssh so we can fetch over https.
> Update README.md to change git clone

- packages/ui/src/pages/PreferencesPage.js
Fixes #394.
This disables the 'save' button when the preferences haven't yet been changed. It is also disabled upon saving.
It looks like this:
> feat: disable save button when preferences haven't been changed

- packages/ui/src/index.js
As per https://github.com/neontribe/gbptm/issues/443
found a spot to try setting a listener on the history.
Pros:
- does notice a page change
- does fill the `window.digtalData` variable if it's there
Cons
- won't trigger on page _load_
- can't actually tell if it's being sent to adobe. :man_shrugging: can someone check that?
> 443 dynamic tracking for adobe

- packages/ui/src/components/NearestLooMap.js
- packages/ui/src/css/controls.module.css
- packages/ui/src/css/messages.module.css
- packages/ui/src/pages/AddEditPage.js
- packages/ui/src/pages/LooPage.js
- packages/ui/src/pages/RemovePage.js
- packages/ui/src/pages/findLooLocationById.graphql
- packages/ui/src/pages/removeLoo.graphql
This PR makes a number of improvements to the toilet removal process:
1. Makes the removal reason field required on the client
2. Adds a clearer message to the loos page for a removed loo
3. When a removal is complete, the user is directed to the removed loo page and shown a thank you message (as you would making any other edit)
4. When viewing a removed loo, a marker is shown on the map
5. When viewing a removed loo, the get directions and edit buttons are disabled
6. Trying to access the edit or removal route for a removed loo will redirect to the index route
fixes #244
> fix: improve removal ux

- package.json
- src/components/EntryForm.js
- src/pages/AddPage.js
- src/pages/EditPage.js
- src/pages/LooPage.js
- src/questionnaireMap.js
- yarn.lock
Difficult to know, without tests if, whether this actually breaks everything.
* Added `<form>` element
* Abstracted `EntryForm` into shared component for `AddPage` and `EditPage`
* Added `react-hook-form` dependency
> refactor: manage EntryForm with react-hook-form

- src/App.js
- src/index.js
- src/pages/EditPage.js
This direct cache manipulation could cause some problems where if the mutation fails, we'll be left with no cached toilet data as it's been evicted before the mutation is called.
#602 implements [this approach](https://www.apollographql.com/docs/react/v3.0-beta/data/mutations/#updating-a-single-existing-entity) to ensuring the cache gets updated with new data after the update loo mutation so the cache manipluation is no longer required
> fix: remove direct cache manipulation

- src/pages/HomePage.js
we don't want the map center to update each time a toilet marker is clicked on however we do want the map to be centered when a user visits /loo/:id directly
> feat: set center to toilet on /loo/:id route

- src/components/LooMap/LooMap.js
Should have the same effect and avoids the console error:
> index.js:1 The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
> fix: avoid :first-child error

- src/components/Sidebar.js
- src/pages/HomePage.js
Accessibility improvement which changes the tab order so that the search/filter controls will be focused before the map.
Includes https://github.com/neontribe/gbptm/pull/729
> fix: reorder DOM so sidebar is before map

- src/components/LooMap/LooMap.js
The focus outline was only appearing briefly before fading away.
> fix: persist map controls focus outline

- src/pages/HomePage.js
this will reduce the number of initital requests on the home page by one
> fix: skip find loo by id query

- src/Apollo.js
- src/Auth.js
- moves Apollo Client setup outside of react component
- moves some AuthProvider functions outside of the provider component to allow our Apollo Auth Link to check for the auth token in LocalStorage
this isn't causing any issues at the moment but if we had a parent wrapping component it would cause the apollo client to be recreated every rerender
> refactor: construct apollo client outside of react component

- src/components/LooMap/LooMap.js
- src/components/ToiletDetailsPanel.js
- reduces max height of toilet details panel on mobile (forgot to take into account browser "chrome"
- hides zoom controls on mobile so they don't overlap with the search bar (zooming can be done with pinch gesture)
- reorders toilet details sections on mobile (move opening times and last verified to bottom)
fixes #782
fixes #783
> fix: mobile toilet details panel order and height

- src/pages/AddPage.js
Updates map center when the map moves to ensure the selected loo location is added to the mutation variables
Fixes #769
> fix: update map center on add page

- src/components/EntryForm.js
- src/pages/AddPage.js
- src/pages/EditPage.js
Fixes #762 
Worked with Rachel to make the following changes:
> * Adjusting it so that the map takes up a higher % of the viewpoirt height helps with the 'lots of white space' part of the problem.
> * Removing the corners deals with the misconception of the form 'masking' the map.
> * Removing the title then permits the user to still view the initial content of the form before it gets cut off at the viewport height.
> fix: update add and edit page appearance

- src/components/LooMap/LooMap.js
- src/explorer/explorer.module.css
~Can't reproduce locally so I'm testing against now.sh.~
This is the best/only solution I could find :/
Fixes #776
>  fix: load all map tiles for Safari browser

- src/components/ToiletDetailsPanel.js
I'm not sure if we want these in a specific order.
Note that the "Urinal Only" duplicates the icon for "Gender Neutral".
Fixes #764
> feat: list all toilet features in details panel

- src/components/LocationSearch/LocationSearch.js
- src/components/LocationSearch/useNominatimAutocomplete.js
- src/components/LocationSearch/usePlacesAutocomplete.js
Something's not working with the Google Places session tokens which is making the cost unsustainable. This PR reverts to using the Nominatim geocoder for our search results.
- adds a `useNominatimAutocomplete` hook to fetch search results based on the query input
- swaps `useNominatimAutocomplete` for `usePlacesAutocomplete`
- tweaks `usePlacesAutocomplete` to make the API more similar to `useNominatimAutocomplete` and generic which should mean future search provider changes will not require changes to the `LocationSearch` component itself
> feat: use nominatim geocoder for search

- public/index.html
- src/components/LocationSearch/LocationSearch.js
- src/components/LooMap/LocateMapControl.js
Adding plausible events to see how many users are searching or using geolocate to find toilets.
Related to issue #1032. We want to double check our assumption that users are finding it hard to find toilets near them, and aren't using geolocate.
> feat: add plausible events

- src/components/ToiletDetailsPanel.js
This fixes a problem where the currently highlighted day on the toilet details panel was off by one, meaning that the wrong day was highlighted
| Before  | After |
| ------------- | ------------- |
| <img width="1084" alt="Screenshot 2021-12-24 at 21 34 18" src="https://user-images.githubusercontent.com/1771189/147372726-1d493028-de9d-45f5-b778-b1ca27ed9626.png"> | <img width="1076" alt="Screenshot 2021-12-24 at 21 33 58" src="https://user-images.githubusercontent.com/1771189/147372731-df56020a-6e57-4d2b-b200-5bca621eb67b.png"> |
> Fix highlighted day off by one error

- src/api-client/operations/findLooNamesByIds.graphql
- src/api/resolvers.ts
- src/api/schema.graphql
- src/components/Filters.tsx
- src/components/LooMap/AccessibilityIntersection.tsx
- src/components/LooMap/AccessibilityList.tsx
- src/components/LooMap/LooMap.tsx
- src/components/LooMap/Markers.tsx
- src/components/MapState.tsx
- src/components/Sidebar/Sidebar.tsx
- src/lib/loo.ts
- src/pages/index.tsx
Fixes @falconx's accessibility overlay so that it works correctly with the new toilet clustering & geohash loading infrastructure.
I don't 100% like how I've gotten this to work but now we're nearing (fingers crossed) the last few big parts of the nextjs migration the next big thing after launching will be to tidy up stuff like my half-baked implementation here.
deployment: https://gbptm-next-3k5ig1cyq-neontribe.vercel.app/
Used a slightly awkward way of recording which toilets have been loaded in already for use in the accessibility list.. essentially populating a `loadedGroups` object in the map state as chunks are loaded in with compressed data (id, lat/lng, filter). In future we could probably just tap into the apollo cache, or remove chunks as they are loaded in/ out of the map …
> Fix accessiblity overlay

- package.json
- yarn.lock
Couldn't ugprade `graphql` to latest v 16 because `graphql-codegen-apollo-next-ssr` doesn't support it yet. We could look into why and open a PR there if we need a v16 feature (not really sure what this release adds though) but for now should be fine
> Upgrade gql to 15.8.0

- src/api-client/schema.ts
- src/api-client/withApollo.tsx
- src/api/resolvers.ts
- src/pages/api/index.ts
Fixes the import of the apollo client schema which started returning a promise after the recent package upgrade in #340 
Splits out the executable schema init into its own file that can be supplied with the directives that turned into promises after the upgrade
> Fix apollo client schema

- src/components/LooMap/LooMap.tsx
- src/components/LooMap/Markers.tsx
prior to this change, the map crashed after searching for a location and selecting a loo because of a conflict between the loaded loo latitude and longitude and the loaded loo state lat/lng
this also fixes a useEffect which ran infinitely after you searched. this disables exhaustive deps so that the effect only runs if the search location changes
> Fix loo selection after search

- src/components/EntryForm.tsx
There were some API changes around the `register` method provided by the `react-hook-form` library in v 7.0 this fixes our use of the library.
> Fixes for `react-hook-form` v7

- package.json
- tests/puppeteer/editPage.test.js
- yarn.lock
Bumps apollo-server to `2.25.3` to avoid a vulnerability in lower versions
> Upgrade apollo-server to avoid vulnerability

- src/components/LooMap/LooMap.js
Quote from https://www.openstreetmap.org/copyright
> You are free to copy, distribute, transmit and adapt our data, as long as you credit OpenStreetMap and its contributors.
This attribution code was adapted from https://react-leaflet.js.org
**Preview**
>  fix: OpenStreetMap attribution required by license

- cypress/integration/desktop/edit.spec.ts
- cypress/integration/desktop/index.spec.ts
- cypress/integration/mobile/edit.spec.ts
- cypress/integration/mobile/index.spec.ts
- src/components/EntryForm.tsx
- src/components/Sidebar/Sidebar.tsx
- src/pages/_app.page.tsx
<details>
<summary>Adds a count so that there is a visual indication of how many filters are applied:</summary>
</details>
<details>
<summary>Stack buttons only on smaller viewports:</summary>
</details>
Fixes how the map state is shared so that it is cleared when visiting the edit/add pages and kept on the root and when navigating between loos
> Count applied filters, align cta buttons on mobile

- next.config.js
This adds a rewrite to the next config so that we can still direct people to the explorer app, which will be hosted separately for now here: https://explorer.toiletmap.org.uk
> Migration | Rewrite Explorer

- yarn.lock
Many deps were pointing to `.npmjs.org` and on older versions with security vulnerabilities from the pre-migration days.
> Upgrade deps in the yarn lockfile

- next.config.js
- package.json
- yarn.lock
These modules were including the null coalesce operator in the build, meaning that the app crashed at runtime on older browsers. 
This change ensures that these modules are transpiled as part of our build step using `next-transpile-modules` https://github.com/martpie/next-transpile-modules
Tested in Chrome 72 and the website now renders the map instead of erroring at runtime
> Transpile react-leaflet and markercluster 

- sentry.client.config.js
Sentry very kindly upgraded us to a sponsored plan, meaning that we have a 5 million(!) cap on the number of errors we can record. 
Given this is a very high number compared to the traffic we get, let's sample more!
> Sentry sample rate modification

- src/components/LooMap/LooMap.tsx
- src/pages/_app.page.tsx
- src/pages/api/index.page.ts
A border shadow existed around the controls on the map:
This PR removes it and also applies a "bounded" cache to the apollo server to protect us against a potential DOS attack: https://www.apollographql.com/docs/apollo-server/performance/cache-backends/ — this is strongly recommended in the linked documentation
> fix: border on controls, and add bounded cache for persisted query vuln

- src/components/ToiletDetailsPanel.tsx
- src/pages/_app.page.tsx
When applying titles to the rendered font awesome icons, we were experiencing a non-matching id error between the client and the server. We work around this problem by setting the title on a parent element.
This will hopefully reduce some of the noise we get on our Sentry logs
A small change is also made here: https://github.com/neontribe/gbptm/pull/1372/files#diff-4eddf35da52afa00c787cc8b42c10e7c04def3ecf6a4f83686bbdad6135ca0d4R8 to follow the font awesome docs for when using the library with nextjs
> Fix SSR error

- src/components/LooMap/LooMapLoader.tsx
Only on iPhones loo pages were not loading with the loo marker in focus and the map centred on it. Instead, the page was loaded with the loo deail panel but centred on central London, our default starting location.
We solve this issue by ensuring that the loo map is rendered in time to pick up the props that the /loos/[id] page sets to determine the marker focus and map centre
Locally and on a staging instance
> Loading loo pages on iPhone

- README.md
- sentry.server.config.js
We neglected to updated this to match the client side sample rate when we got bumped to a premier tier plan
Updates our Readme with logo to indicate suport from Sentry:
> chore: update sentry serverside sample rate to match client

- .github/workflows/cypress-e2e-firefox.yml
Firefox was breaking occasionally during our tests. This will hopefully ensure that the image we use remains stable
> fix: use the official cypress firefox container image

- src/components/Feedback/Feedback.tsx
- src/components/Header/Header.tsx
A change to the copy in our new feedback form to hopefully prompt users to remember the "human factor" in developing the project and keep their feedback fair, without directing their feelings so much at us
> Friendly feedback (hopefully)

- src/components/LooMap/LooMap.tsx
- src/components/LooMap/LooMapLoader.tsx
- src/pages/_app.page.tsx
We prevent users from zooming out too far and displaying the map so that it wraps around which causes a noticeable slowdown. Users can still zoom out to an international level with this change, just not further.
> Add a minimum zoom to the main map

- .github/workflows/cypress-e2e-chrome.yml
- .github/workflows/cypress-e2e-firefox.yml
According to the Cypress Dashboard, this will save us another 20 seconds-ish for each run
> Add another machine to Cypress action run

- src/api/schema.graphql
- src/pages/api/index.page.ts
We increase the TTL (time to live) of our Redis geohash cache to 6 hours because editing/adding loo cache invalidation is working as expected.
This means in practice that we can make even fewer requests to Mongo for loo information during day-to-day usage of the website
> Redis cache TTL increase

- README.md
- src/pages/about.page.tsx
We update the readme to reflect our new sponsorship from Vercel
Remove a duplicate paragraph from the About page
> feat: update the readme to reflect Vercel support and fix duplicated paragraph on about page

- next.config.js
- src/components/LocationSearch/LocationSearch.tsx
We had a user report that the keyboard on their mobile device wasn't closing after they finished searching for a location using the LocationSearch component.
This change ensures that we `blur` the search input when a search result is selected, causing the keyboard and menu to close - allowing users to immediately see the result of selecting the search result.
> "When I search for toilets in a specific location, the keypad stays on the screen so I can't see the map, which makes this unusable."
* Enables console logs once again in development
> Close the keyboard for the location search on mobile

- package.json
- src/pages/voyager/index.page.tsx
- yarn.lock
`graphql-voyager` was last published to npm two years ago and several vulnerabilities are being reported by dependabot in this package.
I've disabled it for now, but we could look into enabling if we need it in the future, as development still seems quite active in the repo?
> chore: disable voyager for now

- src/api/graphql/resolvers.ts
- Restricts the page size for our pagination api to 100 toilets per-page.
> add a size limit to pagination

- package.json
- pnpm-lock.yaml
- src/@types/resolvers-types.ts
- src/api-client/operations/looReportFragment.graphql
- src/api-client/operations/looReportHistory.graphql
- src/api/graphql/resolvers.ts
- src/api/schema.graphql
- src/components/ToiletDetailsPanel.tsx
- src/lib/features.tsx
- src/lib/openingTimes.ts
- src/pages/explorer/index.page.tsx
- src/pages/explorer/loos/[id]/index.page.tsx
- src/pages/explorer/search.page.tsx
- Render toilet report history, allowing for users and @gailramster to see edit history properly on the website.
- Contributor names are redacted until we can check if users have the proper permissions to view them once again.
- User interface is quite minimal and has problems, it does the job - the purpose of this PR is mainly to bring the functionality back as it was missing in the initial Postgres migration
- Changes the sql seed so that system generated `*-location` contributors aren't included anymore, this is because when the db is seeded, only one audit record is made meaning that the two won't match up in the CODE environment. In PROD there is a 1-1 mapping between audit records and contributors listed
Report history is shown in a timeline format that looks like this:
> Surface loo report information in Explorer

- src/api/graphql/resolvers.ts
- src/pages/explorer/loos/[id]/index.page.tsx
- Previously, the report diffing logic was a bit off, not provding a true representation of what changed between reports. This amends that logic so that each timeline entry gives a realistic idea of what has changed, removing some noise.
- Fixes the table column alignment so it's less noisy and easier to read
> Explorer | Fix diff logic, improve table spacing + consistency

- src/config.ts
This should solve #1463 and is an adjustment to the editMinZoom in config.ts which makes the min zoom consistent across index and add/edit page.
Tested in local dev environment as change is minor.
If applicable to your changes, have you:
If applicable to your changes, have you:
> fix: add/edit page min-zoom consistent with index page

- src/components/Feedback/Feedback.tsx
- src/design-system/components/Button/Button.css
If we want specific sizes for buttons we should add new variants. I think for now we shouldn't constrain the size of the buttons rather let them either fill the space given by the parent or be as large as they need to be as determined by their children.
Removes the max-width for buttons
- Testing via Chromatic as this is only a visual change to the width of the button
n/a
n/a
> style: remove max-width for buttons

- pnpm-lock.yaml
- src/components/LocationSearch/useNominatimAutocomplete.ts
- Catch spurious errors in our Nominatim location fetch routine which was causing our Firefox Cypress test to fail on the uncaught exception
> Potential fix for failing edit test on firefox

- .github/workflows/cypress-e2e-chrome.yml
- .github/workflows/cypress-e2e-firefox.yml
- cypress.config.ts
- This was adding a lot of complexity for a use case that doesn't happen very often.
- Pass `--headed=true` to fix an issue with Cypress v11 when using Chrome 117 (issue related: https://github.com/cypress-io/cypress/issues/27804#issuecomment-1721476731)
> Remove pr_target privileged run label check for Cypress Actions

- next.config.js
- src/components/Providers.tsx
We use a same-domain proxy for our Plausible anlytics to reassure
privacy tools that we control our data carefully.
The support for doing this in Plausible changed from DNS level changes
to preferring local proxies. This is well-supported by next-plausible:
https://plausible.io/docs/proxy/guides/nextj
> Update to new Plausible proxy methods

- src/components/LooMap/Markers.tsx
- src/design-system/components/stylesheet.css
| Before | After |
|--------|--------|
| <img width="1728" alt="before" src="https://github.com/public-convenience-ltd/toiletmap/assets/76776/48ef0aa8-cd3e-409c-acf9-4012a85825d8"> | <img width="1728" alt="after" src="https://github.com/public-convenience-ltd/toiletmap/assets/76776/e73585c6-1624-4799-bdb4-f4857a1aa306"> |
How have you tested your changes?
- Locally with `pnpm dev`
If applicable to your changes, have you:
If applicable to your changes, have you:
> Use a custom cluster marker style

- src/components/LooMap/LooMap.tsx
- src/components/Sidebar/Sidebar.tsx
We had some event tracking on our filter buttons for a while. I think we've learned anything we were going to from that.
I've turned that off (partly for the money, and partly to keep focus)
I've turned on some tracking on the map styles control button so we can maybe get some idea...
We don't track on local or previews, so we'll have to wait till this merges and then for @mxdvl's PR to land....
I've set up the plausible side already...
> Switch plausible tracking to map styles control

- package.json
- pnpm-lock.yaml
- schema.prisma
- src/api/prisma/queries.ts
- src/components/Feedback/Feedback.tsx
- src/design-system/components/InputField/InputField.tsx
- src/pages/api/feedback/index.page.ts
- supabase/migrations/20240823182342_feedback_table.sql
- This improves the feedback form, adding an optional email field so we can get in touch with individuals who wish to be contacted back
- This has been covered by changes to our privacy policy in: #1715  
- We also record the route so we know which page the user sent the feedback from
- Some small improvements to accessibility and width on mobile
> Add optional email field for feedback, record feedback in db

- .github/workflows/cypress-e2e-chrome.yml
- We've been having persistent issues with our Cypress binary cache not being persisted properly across CI runs, hopefully this will resolve the issue after bumping the version of the Cypress gh action that we use to v6
- Maybe it won't, maybe it will : -)
> Set gh actions cypress action to v6 

- content-collections.ts
- package.json
- pnpm-lock.yaml
- https://github.com/remarkjs/remark-gfm install this to allow a wider range of markdown in our blog posts
> Install remark-gfm
