public-convenience-ltd/toiletmap

api/public/loo.js, models/loo.js
=> Fix loo regeneration which duplicated attributions

packages/ui/src/components/map/NearestLooMap.js, packages/ui/src/index.js, packages/ui/src/pages/AboutPage.js, packages/ui/src/pages/AddEditPage.js, packages/ui/src/pages/AuthCallback.js, packages/ui/src/pages/HomePage.js, packages/ui/src/pages/LoginPage.js, packages/ui/src/pages/LooPage.js, packages/ui/src/pages/PreferencesPage.js, packages/ui/src/pages/RemovePage.js, packages/ui/src/redux/modules/auth.js, packages/ui/src/redux/sagas/auth.js
closes #181
This turned into a fair-sized refactor it is cleaner as a result but
there's still a way to go
=> fix: suppress double request on app start

packages/opening-hours/index.js, packages/opening-hours/package.json, packages/ui/package.json, packages/ui/src/api.js, packages/ui/src/pages/AddEditPage.js, yarn.lock
=> fix: lightweight opening-hours

packages/ui/src/pages/LooPage.js
Suspiciously easy implementation of linking to Apple's Map API. See #218 for more details.
closes #218
=> feat: link to directions on loo page

packages/ui/src/components/LooMap.js, packages/ui/src/components/css/loo-map.module.css
=> fix: display crosshair on add/edit

packages/ui/src/css/colors.css, packages/ui/src/css/controls.module.css, packages/ui/src/pages/AddEditPage.js
=> Obvious update prevention

packages/ui/src/components/LooListItem.js, packages/ui/src/components/LooMap.js, packages/ui/src/components/NearestLooMap.js, packages/ui/src/components/css/loo-map.module.css, packages/ui/src/pages/HomePage.js
=> Loo numbers

packages/ui/src/pages/css/home-page.module.css
fixes #257
not sure what the original IE11 issue was but this looks fine to me.
=> fix: fill remaining viewport with map

packages/ui/src/components/LooListItem.js
=> fix: humanize distances

packages/ui/package.json, packages/ui/src/config.js, packages/ui/src/index.js, yarn.lock
=> feat: add analytics for page views

README.md
Discovered whilst trying to use the repo to find the app
=> Fix link to app

packages/ui/src/pages/AboutPage.js
=> fix: issue #316 typo

packages/ui/src/components/Header.js, packages/ui/src/components/css/header.module.css, packages/ui/src/components/css/layout.module.css, packages/ui/src/css/global.css
=> fix: shrink header on small viewports

packages/ui/src/pages/AddEditPage.js
=> fix: no search box on add toilet page

packages/ui/package.json
Tagging commit which resolves disappearing search box issue until next release of the `leaflet-control-geocoder` project.
=> fix: tag commit which fixes evt propogation issue

packages/admin/package.json, yarn.lock
Updates:
* @material-ui/core
* @material-ui/icons
* material-ui
* chart.js
=> build: update chart.js and material-ui to latest versions

packages/admin/src/components/Search.js
* Improves labels
* Moves area search from a dropdown into an autocomplete field.
=> feat: improve search controls

packages/explorer/README.md, packages/explorer/src/components/Home.js, packages/explorer/src/css/home.module.css
Basic intro page for the explorer
=> Explorer index page

packages/ui/src/pages/AddEditPage.js
* noticed this while testing, @edpe saw you made it a few months ago. Not sure if changed intentionally, so thought I'd make sure :smile:
=> fix: apostrophe

.yarnrc, packages/ui/package.json, packages/ui/public/adobe-digital-data.js, packages/ui/public/index.html, packages/ui/src/components/Footer.js, packages/ui/src/components/PageLayout.js, packages/ui/src/components/Tracking/AdobeTracking.js, packages/ui/src/components/Tracking/CookiePopup.js, packages/ui/src/components/Tracking/CookiePopupButton.js, packages/ui/src/components/Tracking/Tracking.js, packages/ui/src/components/Tracking/index.js, packages/ui/src/components/css/cookie-popup.module.css, packages/ui/src/config.js, packages/ui/src/index.js, yarn.lock
Initial setup for tracking and cookie popup, needs copy and more thinking about how toggling the tracking works. (basically just fix the TODOs)
=> feat(#415): add initial tracking scripts and popup

packages/ui/src/components/Tracking/CookieBox.js
Forgot to remove, sorry!
Removed the  unnecessary first `<p>` that we missed
=> fix: remove now unnecessary first <p> that we missed

packages/ui/src/components/Tracking/CookieBox.js
update copy as per Gail's email and corrected Grammer as per Harry's suggestion
=> fix: update copy as per Gail's email

packages/explorer/package.json, packages/ui/package.json, yarn.lock
fixes #445 
- add cross-env to ui and explorer packages
=> fix: add cross-env

packages/explorer/package.json, packages/explorer/src/components/Home.js, packages/explorer/src/css/home.module.css, yarn.lock
=> fix: wrong links on explorer homepage

packages/explorer/src/components/Search/index.js
- pagination settings now have an effect
- to make a new query the search button must be pressed, rather than just having
a half-working automatic query system, which could also cause problems
- fixed an error with setting the page to 1 when there was no data
resolves #503
=> fix: explorer search broken in many ways

src/components/PageLoading.js, src/components/css/app.module.css, src/index.js
Not sure if we have designs coming for this?
=> feat: introduce PageLoading component

src/api/db/core.js
=> fix: allow empty text fields

package.json, src/components/Drawer.js, src/components/PageLayout.js, yarn.lock
Simple slide rtl for now but I've asked Rachel what animation she'd like to see.
=> feat: animate drawer

src/components/Filters.js, src/components/PageLayout.js, src/components/arrow-right.svg, src/components/useNearbyLoos.js, src/config.js, src/pages/HomePage.js
This will need changing as of https://github.com/neontribe/gbptm/pull/673/files
=> feat: filter nearby toilets

src/components/Filters.js, src/components/PageLayout.js, src/components/arrow-right.svg, src/components/useNearbyLoos.js, src/config.js, src/pages/HomePage.js
=> Revert "feat: filter nearby toilets"

package.json, src/api/db/manage/generate/index.js, yarn.lock
This is especially reassuring when running against a remote DB, which
can take a while...
=> feat: reassuring output when running generate job

src/components/ToiletDetailsPanel.js
add collapse arrow and back to top button
=> feat: add collapse arrow and back to top

package.json, src/components/LooMap/LooMap.js, src/components/ToiletDetailsPanel.js, src/index.js, src/pages/HomePage.js, yarn.lock
Essentially we set the `bottom` css value of the map controls whenever the height of the `ToiletDetailsPanel` changes
=> Move controls

src/components/ToiletDetailsPanel.js
with some smooth scrolling too
=> refactor: make back to top button a link

src/components/PageLayout.js
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main#Browser_compatibility
=> fix: add main role

src/pages/AboutPage.js
`<ul>` was nested inside a `<p>`.
=> fix: about page semantics

src/components/LocationSearch/LocationSearch.js, src/components/Sidebar.js
- fixes `getMenuProps` downshift error
=> Fix getMenuProps downshift error

src/components/LooMap/LooMap.js
fighting leaflet css over specificity
=> fix: map controls border radius

src/components/ConditionalWrap.js, src/components/EntryForm.js, src/components/Switch.js
=> fix: align opening hours columns

src/components/Header/Header.js, src/components/Header/MainMenu.js
set the drawer state to closed whenever a menu link is clicked
Fixes #781
=> fix: close drawer menu on link click

src/components/Header/MainMenu.js
=> feat: add logout button

src/components/Drawer.js, src/components/Portal.js
=> fix: drawer display on Safari

package.json, yarn.lock
Fixes #763 (I'm not sure why though)
Reverts https://github.com/neontribe/gbptm/commit/22ba540b879e31501afffa700a7502e6ca53bdf6
=> fix: data fetching for edit page

src/components/Header/MainMenu.js
Something went back in the last bunch of merges.
=> fix: header display

src/Auth.js, src/Router.js, src/components/Header/MainMenu.js, src/explorer/Layout.js, src/history.js, src/index.js, src/pages/EditPage.js
trying to reduce the amount of indirection
=> chore: move router history to index

src/components/Header/Header.js
=> feat: show covid notification

src/pages/AboutPage.js
=> feat: add information about Explorer to the about page

src/pages/EditPage.js
=> fix: avoid form revalidation on tab focus

src/components/EntryForm.js, yarn.lock
Fixing this issue: https://github.com/neontribe/gbptm/issues/1006
=> fix: only allows number input

package.json, src/components/LooMap/LooMap.tsx, src/components/LooMap/Markers.tsx, src/components/MapState.tsx, src/pages/loos/[id]/edit.tsx, src/pages/loos/[id]/index.tsx, yarn.lock
also removes the focused loo from the leaflet loo group so that the marker overlap issue is avoided
=> feat: lifts the currently focused loo up to the map state

src/components/LocationSearch/useNominatimAutocomplete.ts, src/components/LooMap/LooMap.tsx, src/components/LooMap/Markers.tsx, src/components/ToiletDetailsPanel.tsx, src/pages/index.tsx
Proposal to add a close button to the toilet details panel so that users can exit the panel should they so desire. Simply clears the focused loo and redirects to the root of the web app. Includes some small tidyups and re-enables the distance measure
=> Proposal: Close button

package.json, src/components/EntryForm.tsx, src/components/LocationSearch/LocationSearch.tsx, src/pages/loos/[id]/edit.tsx, src/pages/loos/add.tsx, yarn.lock
A few bugfixes around the add/edit forms
* Editing a loo and saving without changes doesn't reset the loo location anymore
* Added an error message to the required payment info field if it hasn't been filled in (makes use of @hookform/error-message)
* If you toggle the opening times section open, set an opening time and then toggle the opening times section closed again, you are now able to submit the form
=> Fix add/edit forms

.github/workflows/chromatic.yml
This will help us not reach the Chromatic free account limit so easily
=> Run chromatic on review requested to save quota

.env, .env.local, .env.production, .env.test, .github/workflows/cypress-e2e-chrome.yml, .github/workflows/cypress-e2e-firefox.yml, .gitignore, cypress/integration/desktop/edit.spec.ts, cypress/integration/mobile/edit.spec.ts, cypress/integration/mobile/remove.spec.ts, package.json, src/pages/404.page.tsx, src/pages/500.page.tsx, src/pages/500.stories.tsx, src/pages/loos/[id]/edit.page.tsx, src/pages/loos/[id]/index.page.tsx, src/pages/loos/[id]/remove.page.tsx
* Test suites for editing and removing loos
=> Test suite for Edit/Remove loo pages

src/config.ts, src/pages/api/loos/[id]/revalidate.page.ts, src/pages/loos/[id]/edit.page.tsx, src/pages/loos/[id]/index.page.tsx, src/pages/loos/add.page.tsx
Revalidate for newly added loos so the caching works appropriately
Improve how the revalidate route messaging system works
=> Add loo page revalidate

sentry.client.config.js, sentry.server.config.js
We are in danger of hitting our Sentry sample limit. This lowers our sample rate to a tenth of what it was to avoid this happening.
=> Lower Sentry sample rate

.github/PULL_REQUEST_TEMPLATE.md
I've put together a proposal for a new PR template format 
---
A space to write about what your pull request changes and the reasoning behind your approach.
How have you tested your changes?
Ways of testing could include:
- Writing or extending an end to end test
- Testing your change on a preview deployment
If applicable to your changes, have you:
If applicable to your changes, have you:
=> Propose a new pr template format

src/explorer/Search/index.js
A space to write about what your pull request changes and the reasoning behind your approach.
How have you tested your changes?
Ways of testing could include:
- Writing or extending an end to end test
- Testing your change on a preview deployment
If applicable to your changes, have you:
If applicable to your changes, have you:
=> Fix search following Yoga gql server release

src/explorer/Loo/index.js
Fixes the loo page in explorer after #1380 broke it with the switch to yoga server
=> Fix loo page

.github/workflows/chromatic.yml
* Enables TurboSnap for more efficient Chromatic runs
* Allows Chromatic to run on label as well as review
=> Chromatic improvements

.github/workflows/cypress-e2e-chrome.yml, .github/workflows/cypress-e2e-firefox.yml
Set ubuntu base image to 20.04 so firefox is included
=> Set ubuntu base image to 20.04 so firefox is included

.github/workflows/cypress-e2e-chrome.yml, .github/workflows/cypress-e2e-firefox.yml
- Modifies our GitHub action to run Cypress tests on push to main
=> Run Cypress tests on push to main

.github/workflows/nextjs_bundle_analysis.yml, package.json, src/pages/explorer/index.page.tsx
Uses the https://github.com/hashicorp/nextjs-bundle-analysis action to show us whether our changes are breaching our bundle size ideal (set to 200kb for now)
=> NextJS bundle analysis action

package.json, pnpm-lock.yaml, src/pages/_app.page.tsx
- Installs the `@vercel/analytics` package so we can track user audience information
=> Experiment: Install the @vercel/analytics package

src/components/Feedback/Feedback.tsx, src/components/Header/Header.tsx, src/components/Header/MainMenu.tsx, src/components/Header/hooks.tsx
- Reinstate a feedback box using mui.
- Temporary until the design system is built out a little more and we can create this properly as its own dedicated page.
=> Bring back a feedback box

cypress/e2e/desktop/add.cy.ts, src/components/EntryForm.tsx, src/lib/openingTimes.ts
Reverts public-convenience-ltd/toiletmap#1487 as it breaks some elements of the add / edit functionality
=> Revert "feature: Added an edit all checkbox for opening times form"

.github/workflows/chromatic.yml, .github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/cypress-e2e-chrome.yml, .github/workflows/cypress-e2e-firefox.yml, .github/workflows/nextjs_bundle_analysis.yml, .github/workflows/supabase-migrations-prod.yml, .github/workflows/supabase-migrations-stage.yml, package.json
Skips run for dependabot
Updates pnpm gh action runner
=> use latest version of pnpm action setup

.storybook/preview.js, src/components/EntryForm.tsx, src/design-system/components/InputField/InputField.css, src/design-system/components/InputField/InputField.stories.tsx, src/design-system/components/InputField/InputField.tsx, src/design-system/components/InputField/index.tsx, src/design-system/components/stylesheet.css
#1543 
Added input field to design system using CSS styling only. 
Replaced existing input field with new component
Tested change on a preview deployment
Checked to see if navigable by keyboard both manually and by using dev tools
Colour contrast is accessible according to: https://colourcontrast.cc/ffffff/0a165e
Added input field to Storybook
=> Refactor input field styles

pnpm-lock.yaml
- Bump @babel/traverse from 7.21.5 to 7.23.2
https://github.com/public-convenience-ltd/toiletmap/security/dependabot/131
=> Bump @babel/traverse from 7.21.5 to 7.23.2

.storybook/main.js, .storybook/preview.js, src/design-system/components/Badge/Badge.stories.tsx, src/design-system/components/Button/Button.stories.tsx, src/design-system/components/Icon/Icon.stories.tsx, src/design-system/components/InputField/InputField.stories.tsx, src/design-system/components/RadioInput/RadioInput.stories.tsx, src/design-system/components/Switch/Switch.stories.tsx, src/design-system/components/TextArea/TextArea.stories.tsx
Small PR that adds autodocs to Storybook because I thought it would be a nice things to add. It also refactors some older components to use newer Storybook stuff as they had gone out of date since I'd writtent them.
This was tested locally and passes cypress tests.
Adding all the nice documentation for our future selves and other contributors.
=> Adds autodocs to new design system

.github/workflows/supabase-migrations-stage.yml
- We've recently recreated our stage database, this updates the id
=> Update stage project id

src/components/MapState.tsx
Default to the new map introduced in #1663 for new users without a set preference.
Opened in incognito window, saw the new map.
Opened in a window where I had set to the old map, it kept the old map.
=> Default to protomaps base layer

.github/workflows/cypress-e2e-chrome.yml, src/api/schema.graphql, src/design-system/components/Footer/Footer.tsx, src/design-system/utilities/VisuallyHidden/VisuallyHidden.tsx, src/design-system/utilities/VisuallyHidden/VisuallyHidden.types.tsx, src/globalStyles.tsx, src/pages/About.stories.tsx, src/pages/Contact.stories.tsx, src/pages/Index.stories.tsx, src/pages/Login.stories.tsx, src/pages/Privacy.stories.tsx, src/pages/dataset.page.tsx, src/pages/dataset.stories.tsx
- We add a dedicated page with accompanying licence information so that users are able to download a copy of our complete dataset in either JSON or CSV format under CC BY 4.0
- Descriptive comment added to the PointInput type
- Consistent lower case names for page stories
=> Data download page
